sudo: false
language: elixir
elixir:
  - 1.2.3
otp_release:
  - 18.2.1
before_script:
  - mix local.hex --force
  - mix deps.get --only test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
script: mix test
